/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DividendCalendarThumbnail: typeof import('./src/components/thumbnail/DividendCalendarThumbnail.vue')['default']
    DividendComparisonThumbnail: typeof import('./src/components/thumbnail/DividendComparisonThumbnail.vue')['default']
    DividendEntryEfficiencyThumbnail: typeof import('./src/components/thumbnail/DividendEntryEfficiencyThumbnail.vue')['default']
    DividendSummaryThumbnail: typeof import('./src/components/thumbnail/DividendSummaryThumbnail.vue')['default']
    ErrorBoundary: typeof import('./src/components/ErrorBoundary.vue')['default']
    RecoveryLedgerDialog: typeof import('./src/components/asset/RecoveryLedgerDialog.vue')['default']
    RivalThumbnail: typeof import('./src/components/thumbnail/RivalThumbnail.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThumbnailCardShell: typeof import('./src/components/thumbnail/ThumbnailCardShell.vue')['default']
    ThumbnailPreview: typeof import('./src/components/thumbnail/ThumbnailPreview.vue')['default']
    TossCommunityCopy: typeof import('./src/components/thumbnail/TossCommunityCopy.vue')['default']
  }
}
