<script setup>
import ThumbnailCardShell from './ThumbnailCardShell.vue';
const props = defineProps({ data: { type: Object, default: null } });
const usd = (value) => Number.isFinite(Number(value)) ? `$${Number(value).toLocaleString('en-US', { maximumFractionDigits: 0 })}` : '—';
const pct = (value) => Number.isFinite(Number(value)) ? `${Number(value) >= 0 ? '+' : ''}${(Number(value) * 100).toFixed(1)}%` : '—';
const date = (value) => value?.replace(/-/g, '.');
const crown = (symbol, metric) => props.data?.comparison?.crowns?.[metric]?.has(symbol);
</script>
<template>
    <ThumbnailCardShell class="rival-card" data-thumbnail-kind="rival">
        <template #header v-if="data?.comparison"><div><p>RIVAL</p><h1>{{ data.underlying }} ETF 비교</h1></div><div class="range"><b>{{ date(data.comparison.startDate) }} — {{ date(data.comparison.endDate) }}</b><small v-if="!data.comparison.usesFullYear">약 1년 공통 이력</small></div></template>
        <template v-if="data?.comparison"><section class="base"><span>기준 {{ data.underlying }}</span><b>{{ pct(data.comparison.underlying.priceReturn) }}</b><i /> <small>$10K 투자 시</small><strong>{{ usd(data.comparison.underlying.finalValue) }}</strong></section><section class="matrix"><div class="labels"><span>구분</span><span>최종 평가액</span><span>총수익률</span><span>주가 수익률</span><span>누적 배당금</span><span>기초자산 대비</span></div><div v-for="item in data.comparison.metrics" :key="item.symbol" class="metric" :class="{ selected: item.symbol === data.selectedTicker }"><b>{{ item.symbol }}<small v-if="item.symbol === data.selectedTicker">선택</small></b><strong>{{ crown(item.symbol, 'totalReturn') ? '👑 ' : '' }}{{ usd(item.finalValue) }}</strong><strong>{{ crown(item.symbol, 'totalReturn') ? '👑 ' : '' }}{{ pct(item.totalReturn) }}</strong><span>{{ crown(item.symbol, 'priceReturn') ? '👑 ' : '' }}{{ pct(item.priceReturn) }}</span><span>{{ crown(item.symbol, 'cumulativeDividends') ? '👑 ' : '' }}{{ usd(item.cumulativeDividends) }}</span><span>{{ pct(item.vsUnderlying) }}</span></div></section></template><p v-else class="unavailable">라이벌을 선택하면 공통 가격 이력 기준 비교를 만들 수 있습니다.</p>
        <template #footer>동일 기초자산 ETF · 초기 투자금 $10,000 · 배당 재투자 기준</template>
    </ThumbnailCardShell>
</template>
<style scoped>
.rival-card{box-sizing:border-box;width:720px;height:720px;padding:28px;background:radial-gradient(circle at 100% 0,#dbeafe77,transparent 31%),radial-gradient(circle at 0 0,#eef2ff66,transparent 30%),#fff;color:#0f172a;font-family:Arial,sans-serif}.rival-card :deep(.thumbnail-card-header){flex-direction:column;gap:12px;margin-bottom:15px;padding:16px;border:1px solid #e2e8f0;border-radius:16px;background:#ffffffd9;box-shadow:0 1px 3px #0f172a0d}.rival-card :deep(.thumbnail-card-header)>div:first-child{display:flex;align-items:center;gap:12px}.rival-card :deep(.thumbnail-card-header p){margin:0;color:#0f172a;font-size:30px;font-weight:900;letter-spacing:-.04em}.rival-card h1{margin:0;padding:5px 10px;border:1px solid #e2e8f0;border-radius:6px;background:#f8fafc;color:#475569;font-size:13px}.range{position:absolute;top:43px;right:45px;display:flex;align-items:center;gap:8px}.range b{padding:8px 10px;border:1px solid #e2e8f0;border-radius:8px;background:#fff;font-family:monospace;font-size:13px}.range small{color:#94a3b8;font-size:11px}.base{display:flex;align-items:center;gap:9px;padding:11px 13px;border:1px solid #e2e8f0;border-radius:12px;background:#f8fafcb3;color:#475569}.base span{padding:5px 7px;border:1px solid #fecaca;border-radius:6px;background:#fff1f2;color:#dc2626;font-size:12px;font-weight:800}.base>b{color:#dc2626}.base i{height:18px;border-left:1px solid #cbd5e1}.base small{margin-left:auto;font-size:13px}.base strong{padding:6px 9px;border:1px solid #c7d2fe;border-radius:6px;background:#fff;color:#312e81;font-family:monospace;font-size:15px}.matrix{display:flex;flex:1;margin-top:15px;overflow:hidden;border:1px solid #e2e8f0;border-radius:16px;background:#fff;box-shadow:0 1px 3px #0f172a0d}.labels,.metric{display:grid;grid-template-rows:repeat(6,1fr);min-width:0;flex:1}.labels{max-width:151px;background:#f8fafce6;color:#64748b}.labels span,.metric>*{display:flex;align-items:center;padding:0 12px;border-bottom:1px solid #f1f5f9;font-size:13px}.labels span:first-child,.metric>*:first-child{background:#f1f5f9cc;font-size:15px;font-weight:800}.labels span:nth-child(2),.metric>*:nth-child(2){background:#eef2ff66;color:#312e81}.labels span:nth-child(3),.metric>*:nth-child(3){border-top:1px solid #fecaca;border-bottom:1px solid #fecaca;background:#fff1f2aa;font-weight:800}.metric{border-left:1px solid #e2e8f0}.metric>*{justify-content:center;text-align:center}.metric.selected{background:#eff6ff}.metric.selected>b{color:#4338ca}.metric.selected>b:before{content:'';position:absolute}.metric small{margin-left:4px;color:#2563eb;font-size:10px}.metric strong{color:#0f172a}.unavailable{margin:auto;text-align:center;font-size:25px}.rival-card :deep(.thumbnail-card-footer){padding-top:11px;color:#94a3b8;font-size:12px;text-align:center}
</style>
