<script setup>
const props = defineProps({ data: { type: Object, default: null } });
const usd = (value) => Number.isFinite(Number(value)) ? `$${Number(value).toLocaleString('en-US', { maximumFractionDigits: 0 })}` : '—';
const pct = (value) => Number.isFinite(Number(value)) ? `${Number(value) >= 0 ? '+' : ''}${(Number(value) * 100).toFixed(1)}%` : '—';
const date = (value) => value?.replace(/-/g, '.');
const crown = (symbol, metric) => props.data?.comparison?.crowns?.[metric]?.has(symbol);
</script>
<template>
    <section class="rival-card" data-thumbnail-kind="rival">
        <template v-if="data?.comparison"><header><div><p>RIVAL</p><h1>{{ data.underlying }} ETF 비교</h1></div><div class="range"><b>{{ date(data.comparison.startDate) }} — {{ date(data.comparison.endDate) }}</b><small v-if="!data.comparison.usesFullYear">약 1년 공통 이력</small></div></header><section class="base"><span>기준 {{ data.underlying }}</span><b>{{ pct(data.comparison.underlying.priceReturn) }}</b><i /> <small>$10K 투자 시</small><strong>{{ usd(data.comparison.underlying.finalValue) }}</strong></section><section class="matrix"><div class="labels"><span>구분</span><span>최종 평가액</span><span>총수익률</span><span>주가 수익률</span><span>누적 배당금</span><span>기초자산 대비</span></div><div v-for="item in data.comparison.metrics" :key="item.symbol" class="metric" :class="{ selected: item.symbol === data.selectedTicker }"><b>{{ item.symbol }}<small v-if="item.symbol === data.selectedTicker">선택</small></b><strong>{{ crown(item.symbol, 'totalReturn') ? '👑 ' : '' }}{{ usd(item.finalValue) }}</strong><strong>{{ crown(item.symbol, 'totalReturn') ? '👑 ' : '' }}{{ pct(item.totalReturn) }}</strong><span>{{ crown(item.symbol, 'priceReturn') ? '👑 ' : '' }}{{ pct(item.priceReturn) }}</span><span>{{ crown(item.symbol, 'cumulativeDividends') ? '👑 ' : '' }}{{ usd(item.cumulativeDividends) }}</span><span>{{ pct(item.vsUnderlying) }}</span></div></section></template><p v-else class="unavailable">라이벌을 선택하면 공통 가격 이력 기준 비교를 만들 수 있습니다.</p><footer>동일 기초자산 ETF · 초기 투자금 $10,000 · 배당 재투자 기준</footer>
    </section>
</template>
<style scoped>
.rival-card{box-sizing:border-box;width:720px;height:720px;padding:48px;background:radial-gradient(circle at 100% 0,#dbeafe99,transparent 31%),radial-gradient(circle at 0 0,#eef2ff99,transparent 30%),#fff;color:#0f172a;font-family:Arial,sans-serif;display:flex;flex-direction:column}.rival-card header{padding:17px;border:1px solid #e2e8f0;border-radius:18px;background:#ffffffd9;display:flex;justify-content:space-between;gap:14px}.rival-card header p{margin:0;color:#2563eb;font-size:16px;font-weight:900;letter-spacing:.12em}.rival-card h1{margin:8px 0 0;font-size:36px}.range{text-align:right}.range b{display:block;font-family:monospace;font-size:14px}.range small{display:block;margin-top:5px;color:#94a3b8}.base{display:flex;align-items:center;gap:10px;margin:20px 0;padding:16px;border:1px solid #e2e8f0;border-radius:15px;background:#f8fafc;color:#475569}.base span{padding:5px 7px;border:1px solid #fecaca;border-radius:6px;background:#fff1f2;color:#dc2626;font-size:13px;font-weight:800}.base>b{color:#dc2626}.base i{height:20px;border-left:1px solid #cbd5e1}.base small{margin-left:auto}.base strong{padding:7px 10px;border:1px solid #c7d2fe;border-radius:7px;background:#fff;color:#312e81;font-family:monospace}.matrix{display:flex;flex:1;overflow:hidden;border:1px solid #e2e8f0;border-radius:18px;background:#fff}.labels,.metric{display:grid;grid-template-rows:repeat(6,1fr);min-width:0;flex:1}.labels{max-width:120px;background:#f8fafc;color:#64748b}.labels span,.metric>*{display:flex;align-items:center;padding:0 10px;border-bottom:1px solid #e2e8f0;font-size:14px}.metric{border-left:1px solid #e2e8f0}.metric.selected{background:#eff6ff}.metric.selected>b{color:#1d4ed8}.metric small{margin-left:4px;color:#2563eb}.metric strong{color:#0f172a}.unavailable{margin:auto;text-align:center;font-size:25px}footer{padding-top:18px;color:#94a3b8;font-size:12px;text-align:center}
</style>
