/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AssetManager: typeof import('./components/mypage/AssetManager.vue')['default']
    BookmarkManager: typeof import('./components/mypage/BookmarkManager.vue')['default']
    Breadcrumb: typeof import('primevue/breadcrumb')['default']
    Button: typeof import('primevue/button')['default']
    CalendarGrid: typeof import('./components/CalendarGrid.vue')['default']
    CalendarTickerSelector: typeof import('./components/CalendarTickerSelector.vue')['default']
    Card: typeof import('primevue/card')['default']
    Chart: typeof import('primevue/chart')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    Divider: typeof import('primevue/divider')['default']
    Drawer: typeof import('primevue/drawer')['default']
    FilterInput: typeof import('./components/FilterInput.vue')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IftaLabel: typeof import('primevue/iftalabel')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Password: typeof import('primevue/password')['default']
    ProfileSettings: typeof import('./components/mypage/ProfileSettings.vue')['default']
    RadioButton: typeof import('primevue/radiobutton')['default']
    RecoveryCalculator: typeof import('./components/calculators/RecoveryCalculator.vue')['default']
    ReinvestmentCalculator: typeof import('./components/calculators/ReinvestmentCalculator.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollTop: typeof import('primevue/scrolltop')['default']
    SearchBar: typeof import('./components/SearchBar.vue')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Slider: typeof import('primevue/slider')['default']
    StockCalculators: typeof import('./components/StockCalculators.vue')['default']
    StockChartCard: typeof import('./components/StockChartCard.vue')['default']
    StockHeader: typeof import('./components/StockHeader.vue')['default']
    StockHistoryPanel: typeof import('./components/StockHistoryPanel.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    Toast: typeof import('primevue/toast')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
