<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import { useHead } from '@vueuse/head';
import Button from 'primevue/button';
import Dialog from 'primevue/dialog';
import InputText from 'primevue/inputtext';

type EventRow = { id: number; provider_slug: string; ticker: string; distribution_per_share: string; previous_amount: string | null; average4: number | null; average12: number | null; declared_date: string; ex_date: string; payable_date: string | null; official_url: string };
type Provider = { slug: string; displayName: string; eventCount: number };
type TickerRow = { ticker: string; providerSlug: string; latest: EventRow; historyUrl: string; historyCount: number };
type Index = { providers: Provider[]; tickers: TickerRow[] };
type History = { ticker: string; history: EventRow[] };

const index = ref<Index>({ providers: [], tickers: [] });
const activeProvider = ref('all'); const query = ref(''); const isLoading = ref(true); const error = ref('');
const selected = ref<TickerRow | null>(null); const detailOpen = ref(false); const history = ref<History | null>(null); const isHistoryLoading = ref(false);
useHead({ title: '배당 이력 | 콘텐츠 스튜디오' });

const rows = computed(() => index.value.tickers.filter((row) => (activeProvider.value === 'all' || row.providerSlug === activeProvider.value) && row.ticker.toLowerCase().includes(query.value.trim().toLowerCase())).sort((a, b) => b.latest.ex_date.localeCompare(a.latest.ex_date) || a.ticker.localeCompare(b.ticker)));
const decimal = (value: string | number | null) => value === null || value === undefined ? '—' : `$${Number(value).toFixed(4).replace(/0+$/, '').replace(/\.$/, '')}`;
const change = (event: EventRow) => event.previous_amount === null ? '—' : `${Number(event.distribution_per_share) - Number(event.previous_amount) >= 0 ? '+' : ''}${decimal(Number(event.distribution_per_share) - Number(event.previous_amount))}`;
const chartPoints = computed(() => { const rows = [...(history.value?.history || [])].slice(0, 12).reverse(); const values = rows.map((row) => Number(row.distribution_per_share)); const max = Math.max(...values, 1); const min = Math.min(...values, 0); const span = max - min || 1; return rows.map((row, i) => `${rows.length === 1 ? 50 : (i / (rows.length - 1)) * 100},${100 - ((Number(row.distribution_per_share) - min) / span) * 82 - 9}`).join(' '); });
async function openHistory(row: TickerRow) { selected.value = row; detailOpen.value = true; history.value = null; isHistoryLoading.value = true; try { const response = await fetch(`${row.historyUrl}?t=${Date.now()}`, { cache: 'no-store' }); if (!response.ok) throw new Error(`과거 이력을 읽지 못했습니다 (${response.status})`); history.value = await response.json(); } catch (e) { error.value = e instanceof Error ? e.message : '과거 이력을 불러오지 못했습니다.'; } finally { isHistoryLoading.value = false; } }
onMounted(async () => { try { const response = await fetch(`/content-studio/distribution-index.json?t=${Date.now()}`, { cache: 'no-store' }); if (!response.ok) throw new Error(`배당 이력 색인을 읽지 못했습니다 (${response.status})`); index.value = await response.json(); } catch (e) { error.value = e instanceof Error ? e.message : '배당 이력을 불러오지 못했습니다.'; } finally { isLoading.value = false; } });
</script>

<template>
<section class="distribution-view"><header><p class="eyebrow">OFFICIAL DISTRIBUTION LEDGER</p><h1>배당 이력</h1><p>티커별 최신 배당만 표시합니다. 티커를 선택하면 전체 과거 이력을 확인할 수 있습니다.</p></header>
<p v-if="error" class="notice error">{{ error }}</p><div class="tools"><InputText v-model="query" aria-label="티커 검색" placeholder="티커 검색 (예: TSLY)" /><span>{{ rows.length.toLocaleString() }}개 티커</span></div>
<div class="tabs" role="tablist" aria-label="운용사별 배당 이력"><Button :class="{ active: activeProvider === 'all' }" label="전체" size="small" @click="activeProvider = 'all'" /><Button v-for="provider in index.providers" :key="provider.slug" :class="{ active: activeProvider === provider.slug }" :label="provider.displayName" size="small" @click="activeProvider = provider.slug" /></div>
<p v-if="isLoading" class="notice">불러오는 중…</p><div v-else-if="rows.length" class="table-wrap"><table><thead><tr><th>티커</th><th>최신 배당금</th><th>직전 대비</th><th>4회 평균</th><th>12회 평균</th><th>배당락일</th><th>원문</th></tr></thead><tbody><tr v-for="row in rows" :key="row.ticker"><td><button class="ticker" type="button" @click="openHistory(row)">{{ row.ticker }}</button><small>{{ row.historyCount }}회 기록</small></td><td>{{ decimal(row.latest.distribution_per_share) }}</td><td>{{ change(row.latest) }}</td><td>{{ decimal(row.latest.average4) }}</td><td>{{ decimal(row.latest.average12) }}</td><td>{{ row.latest.ex_date }}</td><td><a :href="row.latest.official_url" target="_blank" rel="noreferrer">보기</a></td></tr></tbody></table></div><p v-else class="notice">조건에 맞는 티커가 없습니다.</p></section>
<Dialog v-model:visible="detailOpen" modal :header="selected ? `${selected.ticker} 배당 이력` : '배당 이력'" :style="{ width: 'min(900px, 96vw)' }"><p v-if="isHistoryLoading" class="notice">과거 이력을 불러오는 중…</p><template v-else-if="history"><section class="history-summary"><strong>최근 {{ history.history.length }}회 공식 기록</strong><a :href="selected?.latest.official_url" target="_blank" rel="noreferrer">최신 공식 원문</a></section><div v-if="chartPoints" class="chart"><svg viewBox="0 0 100 100" preserveAspectRatio="none" role="img" :aria-label="`${history.ticker} 최근 12회 배당금 변화`"><polyline :points="chartPoints" fill="none" stroke="currentColor" stroke-width="2.5" vector-effect="non-scaling-stroke" /></svg></div><div class="history-table"><table><thead><tr><th>배당락일</th><th>배당금</th><th>직전 대비</th><th>4회 평균</th><th>12회 평균</th></tr></thead><tbody><tr v-for="event in history.history" :key="event.id"><td>{{ event.ex_date }}</td><td>{{ decimal(event.distribution_per_share) }}</td><td>{{ change(event) }}</td><td>{{ decimal(event.average4) }}</td><td>{{ decimal(event.average12) }}</td></tr></tbody></table></div></template></Dialog>
</template>

<style scoped>
.distribution-view{display:grid;gap:1.25rem}h1,p{margin-top:0}h1{margin-bottom:.5rem;font-size:clamp(2rem,5vw,3.5rem);line-height:1}.eyebrow{margin-bottom:.45rem;color:var(--studio-accent);font-size:.72rem;font-weight:800;letter-spacing:.12em}header p:last-child,.notice,.tools span,small{color:var(--studio-muted)}.tools{display:flex;align-items:center;justify-content:space-between;gap:1rem}.tools :deep(.p-inputtext){width:min(25rem,100%)}.tabs{display:flex;gap:.45rem;overflow-x:auto;padding-bottom:.25rem}.tabs :deep(.p-button){flex:0 0 auto;border-radius:999px}.tabs :deep(.p-button.active){border-color:var(--studio-accent);color:var(--studio-accent)}.table-wrap,.history-table{overflow:auto;border:1px solid var(--studio-border);border-radius:1rem;background:var(--studio-surface)}table{width:100%;border-collapse:collapse}th,td{padding:.8rem .7rem;border-bottom:1px solid var(--studio-border);text-align:left;white-space:nowrap}th{color:var(--studio-muted);font-size:.75rem;letter-spacing:.05em}.ticker{display:block;padding:0;border:0;background:transparent;color:var(--studio-accent);cursor:pointer;font:inherit;font-weight:800}.notice{margin:0;padding:1rem;border-radius:.75rem;background:var(--studio-surface-subtle)}.error{color:var(--studio-danger)}.history-summary{display:flex;justify-content:space-between;gap:1rem;margin-bottom:1rem}.chart{height:180px;margin-bottom:1rem;padding:1rem;border-radius:.75rem;background:var(--studio-surface-subtle);color:var(--studio-accent)}.chart svg{width:100%;height:100%}@media(max-width:640px){.tools{align-items:stretch;flex-direction:column}.tools :deep(.p-inputtext){width:100%}}
</style>
