<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import Button from 'primevue/button';
type RenderFile = { eventId:number; ticker:string; provider?:string; exDate?:string; verificationStatus?:string; officialUrl?:string; name:string; url:string };
type ContentManifest = { eventId?:number; verificationStatus?:string; officialUrl?:string };
type Bundle = { eventId:number; ticker:string; provider:string; exDate:string; verificationStatus:string; officialUrl?:string; toss?:RenderFile; naver?:RenderFile; social?:RenderFile; socialPng?:RenderFile };
type Modal = { title:string; file:RenderFile; kind:'text'|'image' };
const renders=ref<RenderFile[]>([]); const error=ref(''); const modal=ref<Modal|null>(null); const textContent=ref(''); const copyStatus=ref(''); const provider=ref('all');
const allBundles=computed<Bundle[]>(()=>{const map=new Map<number,Bundle>();for(const r of renders.value){let b=map.get(r.eventId);if(!b){b={eventId:r.eventId,ticker:r.ticker,provider:r.provider||'unknown',exDate:r.exDate||'확인 필요',verificationStatus:r.verificationStatus||'확인 필요',officialUrl:r.officialUrl};map.set(r.eventId,b)}if(r.name==='toss.txt')b.toss=r;if(r.name==='naver-blog.md')b.naver=r;if(r.name==='social-square.html')b.social=r;if(r.name==='social-square.png')b.socialPng=r}return [...map.values()]});
const providers=computed(()=>['all',...Array.from(new Set(allBundles.value.map(b=>b.provider))).sort()]);
const bundles=computed(()=>{const latest=new Map<string,Bundle>();for(const b of allBundles.value.filter(b=>provider.value==='all'||b.provider===provider.value)){const prev=latest.get(b.ticker);if(!prev||b.exDate>prev.exDate||(b.exDate===prev.exDate&&b.eventId>prev.eventId))latest.set(b.ticker,b)}return [...latest.values()].sort((a,b)=>b.exDate.localeCompare(a.exDate)||a.ticker.localeCompare(b.ticker))});
async function load(){error.value='';try{const [renderResponse,contentResponse]=await Promise.all([fetch('/content-studio/renders.json',{cache:'no-store'}),fetch('/content-studio/content.json',{cache:'no-store'})]);if(renderResponse.status===404){renders.value=[];return}if(!renderResponse.ok)throw new Error(`산출물 목록을 읽지 못했습니다 (${renderResponse.status})`);const [renderPayload,contentPayload]=await Promise.all([renderResponse.json(),contentResponse.ok?contentResponse.json():Promise.resolve({})]);const manifests=new Map<number,ContentManifest>();if(Array.isArray(contentPayload.bundles))for(const item of contentPayload.bundles){const manifest=item?.manifest as ContentManifest|undefined;if(typeof manifest?.eventId==='number')manifests.set(manifest.eventId,manifest)}renders.value=Array.isArray(renderPayload.renders)?renderPayload.renders.filter((x:Partial<RenderFile>)=>typeof x.url==='string'&&typeof x.name==='string'&&typeof x.ticker==='string').map((x:RenderFile)=>{const manifest=manifests.get(x.eventId);return {...x,verificationStatus:x.verificationStatus||manifest?.verificationStatus,officialUrl:x.officialUrl||manifest?.officialUrl}}):[]}catch(e){error.value=e instanceof Error?e.message:'산출물 목록을 불러오지 못했습니다.'}}
async function openText(title:string,file?:RenderFile){if(!file)return;copyStatus.value='';textContent.value='불러오는 중…';modal.value={title,file,kind:'text'};try{textContent.value=await(await fetch(file.url,{cache:'no-store'})).text()}catch{textContent.value='내용을 불러오지 못했습니다.'}}
function openImage(title:string,file?:RenderFile){if(file)modal.value={title,file,kind:'image'}}
function downloadName(file:RenderFile){return `${file.ticker.replace(/[^a-zA-Z0-9._-]/g,'_')}-${(file.exDate||'date-unconfirmed').replace(/[^0-9-]/g,'')}-square.png`}
async function copyText(){try{await navigator.clipboard.writeText(textContent.value);copyStatus.value='복사했습니다.'}catch{copyStatus.value='복사 권한을 허용한 뒤 다시 시도하세요.'}}
onMounted(load);
</script>
<template><section class="view"><header><div><p>CONTENT STUDIO ADMIN</p><h1>산출물</h1><small>티커별 최신 배당락 1회만 표시합니다.</small></div><Button label="새로고침" severity="secondary" @click="load"/></header><p v-if="error" class="notice">{{error}}</p><div class="tabs" role="tablist"><Button v-for="item in providers" :key="item" :label="item==='all'?'전체':item" size="small" :class="{active:provider===item}" @click="provider=item"/></div><p v-if="!bundles.length" class="notice">다운로드 가능한 산출물이 없습니다.</p><div v-else class="table-wrap"><table><thead><tr><th>티커</th><th>배당락일</th><th>검증 상태</th><th>공식 출처</th><th>토스</th><th>네이버</th><th>썸네일 미리보기</th><th>썸네일 다운로드</th></tr></thead><tbody><tr v-for="b in bundles" :key="b.eventId"><td><strong>{{b.ticker}}</strong></td><td>{{b.exDate}}</td><td>{{b.verificationStatus}}</td><td><a v-if="b.officialUrl" :href="b.officialUrl" target="_blank" rel="noreferrer">공식 원문</a><span v-else>확인 필요</span></td><td><Button label="열기" size="small" outlined :disabled="!b.toss" @click="openText(`${b.ticker} 토스`,b.toss)"/></td><td><Button label="열기" size="small" outlined :disabled="!b.naver" @click="openText(`${b.ticker} 네이버`,b.naver)"/></td><td><Button label="미리보기" size="small" outlined :disabled="!b.social" @click="openImage(`${b.ticker} 썸네일`,b.social)"/></td><td><a v-if="b.socialPng" :href="b.socialPng.url" :download="downloadName(b.socialPng)">PNG 다운로드</a><span v-else>생성 대기</span></td></tr></tbody></table></div></section><Teleport to="body"><div v-if="modal" class="backdrop" @click.self="modal=null"><section class="modal" role="dialog" aria-modal="true" :aria-label="modal.title"><header><h2>{{modal.title}}</h2><Button icon="pi pi-times" text rounded aria-label="닫기" @click="modal=null"/></header><template v-if="modal.kind==='text'"><pre>{{textContent}}</pre><footer><span>{{copyStatus}}</span><Button label="텍스트 카피" @click="copyText"/></footer></template><iframe v-else :src="modal.file.url" :title="modal.title"/></section></div></Teleport></template>
<style scoped>.view{display:grid;gap:1rem}header{display:flex;justify-content:space-between;align-items:end;gap:1rem}header p{margin:0 0 .35rem;color:var(--studio-accent);font-size:.75rem;font-weight:800;letter-spacing:.1em}h1,h2{margin:0}small,.notice{color:var(--studio-muted)}.tabs{display:flex;gap:.45rem;overflow:auto}.tabs :deep(.p-button){flex:0 0 auto;border-radius:999px}.tabs :deep(.active){border-color:var(--studio-accent);color:var(--studio-accent)}.notice{margin:0;padding:1rem;border:1px solid var(--studio-border);border-radius:.75rem;background:var(--studio-surface)}.table-wrap{overflow:auto;border:1px solid var(--studio-border);border-radius:.75rem;background:var(--studio-surface)}table{width:100%;border-collapse:collapse}th,td{padding:.8rem;border-bottom:1px solid var(--studio-border);text-align:left;white-space:nowrap}th{color:var(--studio-muted);font-size:.75rem}a{color:var(--studio-accent);font-weight:800}.backdrop{position:fixed;inset:0;z-index:1000;display:grid;place-items:center;padding:1rem;background:rgb(9 17 31/.65)}.modal{display:grid;grid-template-rows:auto minmax(0,1fr) auto;gap:1rem;width:min(760px,100%);max-height:calc(100vh - 2rem);padding:1.25rem;border-radius:1rem;background:var(--studio-surface)}.modal header,.modal footer{display:flex;align-items:center;justify-content:space-between}.modal pre{margin:0;padding:1rem;overflow:auto;background:var(--studio-surface-subtle);white-space:pre-wrap}.modal iframe{width:100%;height:min(72vh,720px);border:0;border-radius:.75rem;background:#fff}</style>
